#!/usr/bin/env python3
"""Emit fontIds.h to stdout. Replaces the legacy Ruby one-liners (same algorithm)."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "builtinFonts"
MOD = 2**32
HALF = 2**31


def combo_id(rel_paths: list[str]) -> int:
    total = 0
    for name in rel_paths:
        p = ROOT / name
        if not p.is_file():
            print(f"build_font_ids.py: missing {p}", file=sys.stderr)
            sys.exit(1)
        digest = hashlib.sha256(p.read_bytes()).hexdigest()
        total += int(digest, 16)
    return (total % MOD) - HALF


def main() -> None:
    defines: list[tuple[str, list[str]]] = [
        (
            "BOOKERLY_12_FONT_ID",
            [
                "bookerly_12_regular.h",
                "bookerly_12_bold.h",
                "bookerly_12_bolditalic.h",
                "bookerly_12_italic.h",
            ],
        ),
        (
            "BOOKERLY_14_FONT_ID",
            [
                "bookerly_14_regular.h",
                "bookerly_14_bold.h",
                "bookerly_14_bolditalic.h",
                "bookerly_14_italic.h",
            ],
        ),
        (
            "BOOKERLY_16_FONT_ID",
            [
                "bookerly_16_regular.h",
                "bookerly_16_bold.h",
                "bookerly_16_bolditalic.h",
                "bookerly_16_italic.h",
            ],
        ),
        (
            "BOOKERLY_18_FONT_ID",
            [
                "bookerly_18_regular.h",
                "bookerly_18_bold.h",
                "bookerly_18_bolditalic.h",
                "bookerly_18_italic.h",
            ],
        ),
        ("NOTOSANSJP_14_FONT_ID", ["notosansjp_14_regular.h"]),
        ("NOTOSANSJP_18_FONT_ID", ["notosansjp_18_regular.h"]),
        ("UI_10_FONT_ID", ["ubuntu_10_regular.h", "ubuntu_10_bold.h"]),
        ("UI_12_FONT_ID", ["ubuntu_12_regular.h", "ubuntu_12_bold.h"]),
        ("SMALL_FONT_ID", ["notosans_8_regular.h"]),
    ]

    print("// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh")
    print("#pragma once")
    print()

    for macro, files in defines:
        print(f"#define {macro} ({combo_id(files)})")


if __name__ == "__main__":
    main()
