// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define BOOKERLY_12_FONT_ID (-20281172)
#define BOOKERLY_14_FONT_ID (438244413)
#define BOOKERLY_16_FONT_ID (1839167134)
#define BOOKERLY_18_FONT_ID (-679450484)
#define NOTOSANSJP_14_FONT_ID (-1301692505)
#define NOTOSANSJP_18_FONT_ID (-675829705)
#define UI_10_FONT_ID (22918846)
#define UI_12_FONT_ID (1635686837)
#define SMALL_FONT_ID (674098198)
